# Generated by Django 4.1.7 on 2023-03-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimage',
            name='images',
            field=models.ImageField(blank=True, upload_to='hotel'),
        ),
    ]
