# Generated by Django 4.1.7 on 2023-03-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='images',
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
