# Generated by Django 4.1.7 on 2023-03-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_hotelimage_images_hotelimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HotelImage',
        ),
    ]
