# Generated by Django 4.1.7 on 2023-03-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hotel_url_delete_hotelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Bad'), (1, 'Ok'), (2, 'Average'), (3, 'Fine'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
    ]
