# Generated by Django 4.1.7 on 2023-03-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
