# Generated by Django 4.1.7 on 2023-03-25 04:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contact_email_id_contact_message_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('extra_amenity_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('package_name', models.CharField(blank=True, max_length=100)),
                ('package_city', models.CharField(blank=True, max_length=100)),
                ('package_province', models.CharField(blank=True, max_length=100)),
                ('package_duration', models.CharField(blank=True, max_length=200)),
                ('package_price', models.IntegerField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('url', models.URLField(blank=True, null=True)),
                ('extras', models.ManyToManyField(to='app.extras')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
