# Generated by Django 4.1.7 on 2023-03-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_extras_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailed_description',
            fields=[
                ('dest_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=30)),
                ('days', models.IntegerField(default=5)),
                ('price', models.IntegerField(default=500)),
                ('rating', models.IntegerField(default=5)),
                ('dest_name', models.CharField(max_length=35)),
                ('img1', models.ImageField(upload_to='gallery')),
                ('img2', models.ImageField(upload_to='gallery')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
