# Generated by Django 4.1.7 on 2023-04-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_booking_packbook_package_package_airport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ishotel_name',
            new_name='hotel_name',
        ),
    ]
