# Generated by Django 4.1.7 on 2023-03-29 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_booking_packbook_delete_detailed_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ishotel_name',
            new_name='hotel_name',
        ),
    ]
