# Generated by Django 4.1.7 on 2023-03-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_airport',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
