# Generated by Django 4.1.7 on 2023-04-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_ishotel_name_booking_hotel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='hotel_name',
            new_name='ishotel_name',
        ),
    ]
