# Generated by Django 4.1.5 on 2023-04-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_package_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packbook',
            old_name='ispackage_name',
            new_name='select_package_name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='people',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='packbook',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='packbook',
            name='gender',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='packbook',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='packbook',
            name='people',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
