# Generated by Django 4.1.5 on 2023-04-03 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_ispackage_name_packbook_select_package_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ishotel_name',
            new_name='hotel_name',
        ),
    ]
