# Generated by Django 4.1.7 on 2023-03-28 15:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_package_package_airport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('people', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Packbook',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('people', models.CharField(blank=True, max_length=100)),
                ('ispackage_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ispackage_name', to='app.package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Detailed_description',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ok - 1 star'), (2, 'Average - 2 star'), (3, 'Fine - 3 star'), (4, 'Good - 4 star'), (5, 'Excellent - 5 star')], default=1),
        ),
        migrations.DeleteModel(
            name='HotelBooking',
        ),
    ]
