# Generated by Django 4.1.5 on 2023-04-03 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_ishotel_name_booking_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hotel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ishotel_name', to='app.hotel'),
        ),
    ]
