# Generated by Django 4.1.5 on 2023-04-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_booking_hotel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='hotel_name',
            new_name='select_hotel_name',
        ),
    ]
