# Generated by Django 4.1.5 on 2023-04-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_hotel_name_booking_select_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='people',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='packbook',
            name='people',
            field=models.IntegerField(blank=True),
        ),
    ]
